# Generated by Django 6.1.1 on 2026-09-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_goal', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('icon', models.CharField(default='🦊', max_length=8)),
                ('pin', models.CharField(help_text='4-digit PIN', max_length=4)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('points_week', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1 - CVC'), (2, '2 - Blends'), (3, '3 - Digraphs+')], default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'text'],
            },
        ),
        migrations.CreateModel(
            name='SoundMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(max_length=12)),
                ('count', models.PositiveIntegerField(default=0)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misses', to='game.kid')),
            ],
            options={
                'unique_together': {('kid', 'sound')},
            },
        ),
    ]
