# Generated by Django 5.2.17 on 2026-09-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphemeSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grapheme', models.CharField(max_length=8, unique=True)),
                ('audio', models.FileField(upload_to='sounds/')),
                ('source', models.CharField(choices=[('google', 'Google TTS'), ('custom', 'Teacher upload')], default='google', max_length=10)),
            ],
        ),
    ]
