# Generated by Django 5.2.17 on 2026-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_graphemesound'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, unique=True)),
                ('audio', models.FileField(upload_to='word_sounds/')),
            ],
        ),
    ]
