# Generated by Django 5.2.17 on 2026-09-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_constrain_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'ordering': ['name']},
        ),
    ]
