# Generated by Django 5.2.17 on 2026-09-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_bossfight_words_spelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossfight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bossfight',
            name='words_spelled',
            field=models.TextField(blank=True, default=''),
        ),
    ]
