# Generated by Django 5.2.17 on 2026-09-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_bossfight_id_alter_bossfight_words_spelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsound',
            name='source',
            field=models.CharField(choices=[('custom', 'custom'), ('google', 'google')], default='custom', max_length=10),
        ),
    ]
