# Generated by Django 6.1.1 on 2026-09-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_wordsound_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphemesound',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grapheme_sounds', to='game.class'),
        ),
    ]
