# Generated by Django 6.1.1 on 2026-09-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_shared_google_sounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='egg_cost',
            field=models.PositiveIntegerField(default=50, help_text='Points needed to buy one pet egg.'),
        ),
        migrations.AddField(
            model_name='class',
            name='pets_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('traits_json', models.TextField()),
                ('prompt', models.TextField()),
                ('phrases_json', models.TextField()),
                ('voice_json', models.TextField()),
                ('hatched', models.BooleanField(default=False)),
                ('image_path', models.CharField(blank=True, default='', max_length=200)),
                ('is_companion', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='game.kid')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
