# Generated by Django 6.1.1 on 2026-09-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_pet_hatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hatch_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
