# Generated by Django 5.2.17 on 2026-09-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_pet_hatch_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphemesound',
            name='source',
            field=models.CharField(choices=[('google', 'Google TTS'), ('custom', 'Teacher upload'), ('bundled', 'Bundled recording')], default='google', max_length=10),
        ),
    ]
